# Generated by Django 2.2.7 on 2019-12-01 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_id',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_id',
            new_name='shipping',
        ),
    ]
