# Generated by Django 2.2.7 on 2019-12-06 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_auto_20191206_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='phone_number',
            new_name='phone_num',
        ),
    ]
