# Generated by Django 2.2.7 on 2019-12-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_auto_20191201_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.ManyToManyField(to='amazon.Order'),
        ),
    ]
