# Generated by Django 2.2.7 on 2019-12-01 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0003_product_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.ManyToManyField(db_table='Includes', to='amazon.Order'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('order_id', 'shipping', 'payment')},
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('cmt', models.CharField(default='', max_length=500)),
                ('rating', models.IntegerField(null=True)),
                ('member', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='amazon.Member')),
                ('product', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='amazon.Product')),
            ],
            options={
                'db_table': 'Review',
            },
        ),
        migrations.CreateModel(
            name='Product_picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='amazon.Product')),
            ],
            options={
                'db_table': 'Product_Picture',
                'unique_together': {('product', 'image')},
            },
        ),
        migrations.CreateModel(
            name='Buyer_card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.IntegerField(default=0)),
                ('buyer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='amazon.Buyer')),
            ],
            options={
                'db_table': 'Buyer_Card',
                'unique_together': {('buyer', 'card')},
            },
        ),
    ]
