# Generated by Django 2.2.7 on 2019-12-02 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0004_auto_20191201_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.ManyToManyField(db_table='Includes', related_name='Order_ID', to='amazon.Order'),
        ),
        migrations.AlterField(
            model_name='product_picture',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='amazon.Product'),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(default='', max_length=100)),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='amazon.Category')),
                ('contains', models.ManyToManyField(db_table='Contains', to='amazon.Product')),
            ],
            options={
                'db_table': 'Subcategory',
                'unique_together': {('subcategory_name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Refunds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='amazon.Buyer')),
                ('order', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='amazon.Order')),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='amazon.Product')),
            ],
            options={
                'db_table': 'Refunds',
                'unique_together': {('order', 'product')},
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=100, null=True)),
                ('product', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='amazon.Product')),
            ],
            options={
                'db_table': 'Feature',
                'unique_together': {('product', 'feature')},
            },
        ),
    ]
