# Generated by Django 2.2.7 on 2019-12-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0008_auto_20191206_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_num',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
