# Generated by Django 2.2.7 on 2019-12-06 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0009_auto_20191206_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='phone_num',
            new_name='phone_number',
        ),
    ]
