# Generated by Django 2.2.7 on 2019-12-06 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0011_auto_20191206_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='descript',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='order',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
